name: x-retweet-bot (debug)

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install tweepy

      - name: Inject secrets as env
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: echo "envs set for later steps"

      - name: Check env presence (debug)
        run: |
          python - <<'PY'
          import os
          keys = ["API_KEY","API_KEY_SECRET","ACCESS_TOKEN","ACCESS_TOKEN_SECRET"]
          print({k: bool(os.getenv(k)) for k in keys})
          PY

      - name: Run bot_test.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python bot_test.py
