name: X 自動リツイート Bot (スケジュール)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    # 認証情報は Secrets から設定
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Python セットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 定数設定読み込み (config.env)
        run: |
          # config.env から定数を読み込み、GITHUB_ENV に注入
          echo "読み込み config.env"
          for var in KEYWORDS POLL_MAX_RESULTS MAX_RETWEETS_PER_RUN DRY_RUN LOOKBACK_HOURS LOG_LEVEL STATE_FILE; do
            echo "$var=$(grep -E \"^$var=\" config.env | cut -d'=' -f2-)" >> $GITHUB_ENV
          done

      - name: 依存パッケージインストール
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 環境変数存在チェック
        run: |
          python - <<'PY'
          import os, json
          keys = ["API_KEY","API_SECRET","ACCESS_TOKEN","ACCESS_TOKEN_SECRET"]
          print(json.dumps({k: bool(os.getenv(k)) for k in keys}, ensure_ascii=False))
          PY

      - name: Bot 実行
        run: |
          python bot.py
