name: Debug Secrets (check presence)

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    # ジョブ全体に env を渡す（ここでsecretsをマップ）
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show env presence (safe)
        run: |
          python - <<'PY'
          import os, json
          keys = ["API_KEY","API_KEY_SECRET","ACCESS_TOKEN","ACCESS_TOKEN_SECRET"]
          # Print only presence (True/False), do NOT print actual secret values.
          print(json.dumps({k: bool(os.getenv(k)) for k in keys}, ensure_ascii=False))
          PY

      - name: Run bot_test.py (with same env)
        run: python bot_test.py
